Fix crash with unix sockets
vert-x3/vertx-micrometer-metrics pull request #113
Opened 2020-09-02 09:50 UTC by jotak

Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/112

cc @Stimzz

2020-09-02 12:54 UTC, tsegismont approved these changes
@jotak thanks for the fast turnaround! Approved with some minor changes requested. Can you backport to 3.9 branch?

2020-09-02 12:54 UTC, tsegismont commented on pom.xml
> +    <dependency>
Can you also add the `kqueue` equivalent for those who want to build the project on Macs?

2020-09-02 12:54 UTC, tsegismont commented on src/test/java/io/vertx/micrometer/UnixSocketTest.java
> +  public class DomainSocketClientTriggerVertical extends AbstractVerticle {
```suggestion
  public class DomainSocketClientTriggerVerticle extends AbstractVerticle {
```

Auto-correct? :wink:

2020-09-02 12:54 UTC, tsegismont commented on src/test/java/io/vertx/micrometer/UnixSocketTest.java
> +      h -> vertx.deployVerticle(new DomainSocketClientTriggerVertical(), ch -> allDeployed.complete()));
```suggestion
      h -> vertx.deployVerticle(new DomainSocketClientTriggerVerticle(), ch -> allDeployed.complete()));
```

2020-09-02 12:56 UTC, tsegismont requested changes
Actually it seems there's an issue with the test: actual connection is 0.

2020-09-02 13:11 UTC, jotak commented on src/test/java/io/vertx/micrometer/UnixSocketTest.java
> +  public class DomainSocketClientTriggerVertical extends AbstractVerticle {
It was copy-pasted from the provided reproducer :-)

2020-09-02 13:14 UTC, jotak commented on pom.xml
> +    <dependency>
Can you give me some pointer to how I can do that?
Actually I don't have a mac so I wouldn't even be able to test, it would be better if someone who has one could take care of that? (winks @vietj )

2020-09-02 13:15 UTC, jotak commented
> Actually it seems there's an issue with the test: actual connection is 0.

It should be fixed : need to wait that connection gauge is decreased back to 0 after disconnection.

2020-09-02 13:17 UTC, tsegismont commented on pom.xml
> +    <dependency>
https://vertx.io/docs/vertx-core/java/#_native_bsd_transport

Don't test, we know it works :smile_cat:

2020-09-02 14:32 UTC, jotak commented on pom.xml
> +    <dependency>
So what does it mean? I just add this dependency and voilà, no code change?

2020-09-02 14:36 UTC, jotak commented on pom.xml
> +    <dependency>
(updated)

2020-09-02 14:38 UTC, tsegismont commented on pom.xml
> +    <dependency>
Yes, that's it. Netty will pick the right library at runtime.

2020-09-02 14:39 UTC, tsegismont approved these changes
Thanks @jotak !

2020-09-02 14:39 UTC, merged

2020-09-03 07:55 UTC, jotak commented
backported to 3.9