Implement custom tags provider for HTTP metrics
vert-x3/vertx-micrometer-metrics pull request #124
Opened 2021-06-03 15:15 UTC by jotak

- Allows to implement a CustomTagsProvider interface to provide tags out
of HttpRequest objects.
- Add tests

Fixes https://github.com/vert-x3/vertx-micrometer-metrics/issues/89

2021-06-03 15:29 UTC, jotak commented
Hey @vietj  perhaps it needs a little bit of discussion prior to merging.
To summarize, the feature is about having the ability to customize metric tags out of request data, in particular headers. Basically, tags can be injected for every request based on some request or headers mapping function.

Here I've implemented the most straightforward way, which is by having the user providing a `CustomTagsProvider` mapper into config, something like that:

```java
    vertx = Vertx.vertx(new VertxOptions().setMetricsOptions(new MicrometerMetricsOptions()
      .setRequestsTagsProvider(req -> {
        String user = req.headers().get("user");
        return Collections.singletonList(Tag.of("user", user));
      })
      .setPrometheusOptions(new VertxPrometheusOptions().setEnabled(true))
      .setEnabled(true)));
```

* Pros: it's flexible; The user can create tags the way she wants out of an `HttpRequest` object
* Cons: non-serializable, the `setRequestsTagsProvider` option is executable code, cannot be set up via json

So, we can imagine an alternative where a similar feature would be achieved by providing a (serializable) option, e.g. a list of header keys or a list of pairs [header key, tag name] that would be used for a mapping of headers to tags. But it would be less flexible, no possibility of combining headers, or using other info from `HttpRequest`, or having more complex behaviours. So people may feel limited.

WDYT? Are we good with my first idea; and eventually we can iterate later to enhance the feature by adding serializable options if that's what users want?

2021-06-03 15:32 UTC, jotak commented
PS: CI failure is related to https://github.com/vert-x3/vertx-micrometer-metrics/pull/123

2021-07-08 14:42 UTC, narzach commented
@jotak This is great, thank you for taking the time to make this happen!

IMO your approach is exactly what we need. The serializable option would never be as useful as this is, and IMO would not provide enough value to be worth doing. This gives us full control to set tags based on the context request. For my use cases, I need the ability to do exactly what you're doing, extracting values from HTTP path parameters, query string, or headers, and then injecting corresponding tags. Static tags that are added per app will be useful, yes, but that is trivial and can be done with your setRequestsTagsProvider() approach.

Curious if anyone else has had a chance to look at this?

2021-07-12 07:00 UTC, vietj commented on src/main/java/io/vertx/micrometer/impl/CustomTagsProvider.java
> +public interface CustomTagsProvider<T> {
this interface is in an impl package, I think instead we should rely on Java function types to do this, i.e the provider should simply be a `Function<T, Iterable<Tag>>`

2021-07-12 07:01 UTC, vietj commented on src/main/java/io/vertx/micrometer/MicrometerMetricsOptions.java
> +  private CustomTagsProvider<HttpRequest> requestsTagsProvider;
instead use `Function<HttpRequest, Iterable<Tag>>`

2021-07-12 07:02 UTC, vietj requested changes
use a function instead of a specific new type

2021-07-12 08:31 UTC, jotak commented
@vietj done

2021-07-12 13:57 UTC, vietj requested changes
Documentation

2021-07-22 12:38 UTC, vietj commented on src/main/asciidoc/index.adoc
> +It is possible to define a function that generates additional tags (or labels) for HTTP server metrics.
_You can define_

2021-07-22 12:38 UTC, vietj commented on src/main/asciidoc/index.adoc
> +This function takes an {@link io.vertx.core.spi.observability.HttpRequest} object as a parameter, and returns
Such function

2021-07-23 13:31 UTC, jotak commented on src/main/asciidoc/index.adoc
> +This function takes an {@link io.vertx.core.spi.observability.HttpRequest} object as a parameter, and returns
done

2021-07-23 13:31 UTC, jotak commented on src/main/asciidoc/index.adoc
> +It is possible to define a function that generates additional tags (or labels) for HTTP server metrics.
done

2021-07-23 13:31 UTC, merged